/*******************************************************************************
 * Copyright (c) 2009  Clark N. Hobbie
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Clark N. Hobbie - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_ecf_ipc_semaphore_SemaphoreNative */

#ifndef _Included_org_eclipse_ecf_ipc_semaphore_SemaphoreNative
#define _Included_org_eclipse_ecf_ipc_semaphore_SemaphoreNative
#ifdef __cplusplus
extern "C" {
#endif
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_SUCCESS
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_SUCCESS 0L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_UNKNOWN_ERROR
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_UNKNOWN_ERROR 1L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_PLATFORM_ERROR
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_PLATFORM_ERROR 2L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_UNKNOWN_HANDLE
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_UNKNOWN_HANDLE 3L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_TIMEOUT
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_TIMEOUT 4L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_ACCESS_DENIED
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_ACCESS_DENIED 5L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_NOT_IMPLEMENTED
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_NOT_IMPLEMENTED 6L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_TOO_MANY_INCREMENTS
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_RESULT_TOO_MANY_INCREMENTS 7L
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_METHOD_INTEGER
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_METHOD_INTEGER 0
#undef org_eclipse_ecf_ipc_semaphore_SemaphoreNative_METHOD_FILE_NAME
#define org_eclipse_ecf_ipc_semaphore_SemaphoreNative_METHOD_FILE_NAME 1

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    connect
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_connect
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    increment
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;J)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_increment
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    decrement
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;JJ)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_decrement
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    getValue
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;J)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_getValue
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    supportsGetValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_supportsGetValue
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    setValue
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;JI)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_setValue
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    supportsSetValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_supportsSetValue
  (JNIEnv *, jclass);


/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    createResult
 * Signature: (Lorg/eclipse/ecf/ipc/semaphore/SemaphoreResult;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_createResult
  (JNIEnv *, jclass, jobject, jstring, jint, jint);

/*
 * Class:     org_eclipse_ecf_ipc_semaphore_SemaphoreNative
 * Method:    linkTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_linkTest
  (JNIEnv *, jclass);


JNIEXPORT jint JNICALL Java_org_eclipse_ecf_ipc_semaphore_SemaphoreNative_getNamingMethod
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
