/*******************************************************************************
 * Copyright (c) 2009  Clark N. Hobbie
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Clark N. Hobbie - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _ipc_fifo_FIFOImpl */

#ifndef _Included_org_eclipse_ecf_ipc_fifo_FIFOImpl
#define _Included_org_eclipse_ecf_ipc_fifo_FIFOImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef org_eclipse_ecf_ipc_fifo_FIFOImpl_DIRECTION_READER
#define org_eclipse_ecf_ipc_fifo_FIFOImpl_DIRECTION_READER 0L
#undef org_eclipse_ecf_ipc_fifo_FIFOImpl_DIRECTION_WRITER
#define org_eclipse_ecf_ipc_fifo_FIFOImpl_DIRECTION_WRITER 1L
#undef org_eclipse_ecf_ipc_fifo_FIFOImpl_BLOCKING_MODE_BLOCKING
#define org_eclipse_ecf_ipc_fifo_FIFOImpl_BLOCKING_MODE_BLOCKING 1L
#undef org_eclipse_ecf_ipc_fifo_FIFOImpl_BLOCKING_MODE_NON_BLOCKING
#define org_eclipse_ecf_ipc_fifo_FIFOImpl_BLOCKING_MODE_NON_BLOCKING 2L
/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    createImpl
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_createImpl
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    writeImpl
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;[BII)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_writeImpl
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    readImpl
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;[BII)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_readImpl
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    openImpl
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;I)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_openImpl
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    createNonBlocking
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_createNonBlocking
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    readNonBlocking
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;[BIII)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_readNonBlocking
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    writeNonBlocking
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;[BIII)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_writeNonBlocking
  (JNIEnv *, jobject, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    toActualName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_toActualName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_eclipse_ecf_ipc_fifo_FIFOImpl
 * Method:    connectNonBlocking
 * Signature: (Lcom/lts/ipc/fifo/FIFOResult;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_connectNonBlocking
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_fifo_FIFOImpl_select(
		JNIEnv *env,
		jobject this,
		jobject result,
		jint timeoutMsec);

void FIFOImpl_initialize(JNIEnv *env);

#ifdef __cplusplus
}
#endif
#endif
