/*******************************************************************************
 * Copyright (c) 2009  Clark N. Hobbie
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Clark N. Hobbie - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_ecf_ipc_IPCPackage */

#ifndef _Included_org_eclipse_ecf_ipc_IPCPackage
#define _Included_org_eclipse_ecf_ipc_IPCPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_ecf_ipc_IPCPackage
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_IPCPackage_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_ecf_ipc_IPCPackage
 * Method:    setValue
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_ecf_ipc_IPCPackage_setValue
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_eclipse_ecf_ipc_IPCPackage
 * Method:    createBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_eclipse_ecf_ipc_IPCPackage_createBuffer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
